apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gb7g5oafh-go 
  janus-idp.io/tekton: gb7g5oafh-go
  backstage.io/kubernetes-id: gb7g5oafh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gb7g5oafh-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  